apiVersion: apps/v1
kind: Deployment
metadata:
  name: pageview
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: pageview
  template:
    metadata:
      labels:
        tier: pageview
    spec:
      containers:
      - name: pageview
        image: docker.io/nisburgh/pageview:latest
