apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
    - name: first-container-pageview
      image: nisburgh/pageview:v1.0
      readinessProbe:
        exec:
          command:
          - cat
          - /tmp/health
        initialDelaySeconds:
        periodSeconds: 15
    - name: second-container-netshoot
      image: docker.io/nicolaka/netshoot
      tty: true
